/*表创建*/
CREATE TABLE BOOK(
BOOK_ID VARCHAR(32) NOT NULL,
NAME VARCHAR(100) NULL,
TYPE VARCHAR(50) NULL,
AUTHOR VARCHAR(50) NULL,
TRANSLATOR VARCHAR(500) NULL,
PUBLISHER VARCHAR(50) NULL,
PUBLISH_TIME DATETIME NULL,
STOCK INT NULL,
PRICE MONEY NULL                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
)

CREATE TABLE BORROW(
ID INT NOT NULL,
BOOK_ID VARCHAR(32) NULL,
READER_ID VARCHAR(32) NULL,
BORROW_DATE DATETIME NULL,
BACK_DATE DATETIME NULL,
IS_BACK SMALLINT NULL
)

CREATE TABLE BUY(
BOOK_ID VARCHAR(32) NOT NULL,
NUM INT NULL,
BUY_TIME DATETIME NULL
)

CREATE TABLE READER(
REAER_ID VARCHAR(32) NOT NULL,
NAME VARCHAR(50) NULL,
TYPE VARCHAR(20) NULL,
SEX CHAR(2) NULL,
DAYS_NUM INT NULL,
MAX_NUM INT NULL
)
CREATE TABLE USR(
USR_ID INT NOT NULL,
NAME VARCHAR(50) NULL,
PASS VARCHAR(50) NULL,
IS_ADMIN SMALLINT
)


/*存储过程*/
USE SUN
GO
IF EXISTS(SELECT * FROM SYS.OBJECTS WHERE NAME='BOOK_ID_TJ')
DROP PROC BOOK_ID_TJ
GO

CREATE PROCEDURE BOOK_ID_TJ 
@COUNT INT OUTPUT,
@BOOK_ID_TJ VARCHAR(32),
@DATE_BEGIN DATETIME, 
@DATE_END DATETIME
AS 
SELECT @COUNT=COUNT(BOOK_ID) FROM BORROW  
WHERE BOOK_ID=@BOOK_ID_TJ AND BORROW_DATE BETWEEN @DATE_BEGIN AND @DATE_END

/*测试存储过程*/
GO
DECLARE @COUNT INT ,
        @BOOK_ID_TJ VARCHAR(32),
        @DATE_BEGIN DATETIME, 
        @DATE_END DATETIME
SELECT @DATE_BEGIN='2013/1/16 0:00:00'
SELECT @DATE_END='2013/1/17 1:00:00'
SELECT @BOOK_ID_TJ='1'
EXEC BOOK_ID_TJ
@COUNT OUTPUT,@BOOK_ID_TJ ,@DATE_BEGIN, @DATE_END
PRINT @COUNT
GO

/*触发器代码*/

/*触发器1*/
CREATE TRIGGER INSERT_BOOK_READER 
ON BORROW FOR INSERT 
AS  DECLARE @BOOK_ID_NEW VARCHAR(32),@READER_ID_NEW VARCHAR(32)
	SELECT @BOOK_ID_NEW=BOOK_ID,@READER_ID_NEW=READER_ID FROM INSERTED
	UPDATE BOOK SET STOCK=STOCK-1 WHERE BOOK.BOOK_ID=@BOOK_ID_NEW 
		AND EXISTS(SELECT * FROM BORROW WHERE BOOK_ID=@BOOK_ID_NEW 
		AND READER_ID=@READER_ID_NEW AND IS_BACK='0')
    UPDATE READER SET MAX_NUM=MAX_NUM-1 WHERE READER_ID=@READER_ID_NEW 
		AND EXISTS(SELECT * FROM BORROW WHERE BOOK_ID=@BOOK_ID_NEW 
		AND READER_ID=@READER_ID_NEW AND IS_BACK='0')
/*触发器2*/
CREATE TRIGGER UPDATE_BOOK_READER 
ON BORROW FOR UPDATE 
AS  DECLARE @BOOK_ID_NEW VARCHAR(32),@READER_ID_NEW VARCHAR(32)
    SELECT @BOOK_ID_NEW=BOOK_ID,@READER_ID_NEW=READER_ID FROM INSERTED
    UPDATE BOOK SET STOCK=STOCK+1 WHERE BOOK.BOOK_ID=@BOOK_ID_NEW 
		AND EXISTS(SELECT * FROM BORROW WHERE BOOK_ID=@BOOK_ID_NEW 
		AND READER_ID=@READER_ID_NEW AND IS_BACK='1')
    UPDATE READER SET MAX_NUM=MAX_NUM+1 WHERE READER_ID=@READER_ID_NEW 
		AND EXISTS(SELECT * FROM BORROW WHERE BOOK_ID=@BOOK_ID_NEW 
		AND READER_ID=@READER_ID_NEW AND IS_BACK='1')


/*触发器3*/
CREATE TRIGGER BUYUPDATE_BOOK_READER 
ON BUY FOR INSERT 
AS  DECLARE @BOOK_ID_NEW VARCHAR(32)
    SELECT @BOOK_ID_NEW=BOOK_ID FROM INSERTED
    UPDATE BOOK SET STOCK=STOCK+1 WHERE BOOK.BOOK_ID=@BOOK_ID_NEW 


/*数据库的完全备份*/
USE SUN
GO
BACKUP DATABASE SUN
	TO DISK='F:\备份\FULLBACKUP_SUN'
	WITH INIT
GO

/*数据库差异备份*/
USE SUN
GO
	BACKUP DATABASE SUN
	TO DISK='F:\备份\CBACKUP_SUN'
	WITH DIFFERENTIAL
GO
/*数据库的备份还原*/
USE MASTER
GO
	RESTORE DATABASE SUN
	FROM DISK='F:\备份\FULLBACKUP_SUN'
	WITH NORECOVERY
GO
RESTORE DATABASE SUN
	FROM DISK='F:\备份\CBACKUP_SUN'
	WITH REPLACE
GO
